language: java
jdk:
- oraclejdk8

jobs:
  include:
    - stage: java-adapter-avro-schemas
      before_script: cd java-adaptor-avro-schemas
      before_deploy: cp ../.travis.settings.xml $HOME/.m2/settings.xml
      deploy: 
        provider: script
        script: mvn deploy -DskipTests
        skip_cleanup: true
        on:
          branch: master
    - stage: java-adapter
      before_script: cd testbedadapter
      before_deploy: cp ../.travis.settings.xml $HOME/.m2/settings.xml
      deploy: 
        provider: script
        script: mvn deploy -DskipTests
        skip_cleanup: true
        on:
          branch: master
    - stage: xml-json-to-avro-mapper
      before_script: cd xml-json-to-avro-mapper
      before_deploy: cp ../.travis.settings.xml $HOME/.m2/settings.xml
      deploy: 
        provider: script
        script: mvn deploy -DskipTests
        skip_cleanup: true
        on:
          branch: master
          
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
